# monorepo only work when using virtual manifest
# see: https://github.com/rust-lang/cargo/issues/7467#issuecomment-867632379
[workspace]
members  = ["packages/codegen", "packages/example", "packages/lib"]
resolver = "2"

[workspace.dependencies]
dioxus = "0.6.0-alpha.2"
